(()=>{
const $=s=>document.querySelector(s),cv=$('#game'),c=cv.getContext('2d');
let W=0,H=0,DPR=1,last=0,flashTimer=0,S;
const C=(v,a,b)=>Math.max(a,Math.min(b,v)),R=(a,b)=>a+Math.random()*(b-a),RI=(a,b)=>Math.floor(R(a,b+1));
const CFG={hp:20,cells:200,step:.3,dash:10,win:.3,recover:5,normal:2};
const DEF={slime:{hp:2,dmg:1,kind:'melee',tell:.8,cd:[1.8,3.2],spd:.20,h:92},skeleton:{hp:3,dmg:2,kind:'melee',tell:.9,cd:[2,3.5],spd:.18,h:150},mage:{hp:3,dmg:2,kind:'ranged',tell:1,cd:[2.5,4],spd:.12,h:156},bonobo:{hp:4,dmg:4,kind:'melee',tell:1.15,cd:[2.8,4.2],spd:.16,h:168},dragon:{hp:4,dmg:3,kind:'ranged',tell:1.1,cd:[3,4.5],spd:.10,h:138}};
const imgs={};for(const k of ['hero','slime','skeleton','mage','bonobo','dragon']){imgs[k]=new Image();imgs[k].src='assets/'+k+'.webp?v=4'}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,2);cv.width=W*DPR;cv.height=H*DPR;c.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function sh(a){for(let i=a.length-1;i;i--){let j=RI(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function mk(t,z){let d=DEF[t];return{t,h:d.hp,max:d.hp,l:RI(0,2),z,dead:false,mode:'idle',cool:R(...d.cd),tell:0,move:R(.65,2),flash:0,knock:0}}
function roster(){let a=[],early=sh([...Array(3).fill('slime'),...Array(3).fill('skeleton')]),rest=sh([...Array(6).fill('slime'),...Array(6).fill('skeleton'),...Array(6).fill('mage'),...Array(3).fill('bonobo'),...Array(3).fill('dragon')]);early.forEach((t,i)=>a.push(mk(t,18+i*6+R(-1,1))));rest.forEach((t,i)=>a.push(mk(t,46+i*(145/23)+R(-2,2))));return a}
function reset(){S={run:false,pause:false,clear:false,over:false,time:0,hp:20,dmg:0,z:0,l:1,guard:false,sel:1,ch:[5,5],frac:[0,0],skill:null,finish:0,win:0,dash:null,norm:0,en:roster(),shots:[],fx:[],ptr:null,hitFlash:0};$('#result').classList.add('hide');sync()}
function sync(){$('#hp').textContent=Math.max(0,Math.ceil(S.hp))+'/20';$('#hpf').style.width=C(S.hp/20*100,0,100)+'%';$('#time').textContent=S.time.toFixed(1);$('#fin').textContent=S.finish;$('#g1').style.width=S.ch[0]/5*100+'%';$('#g2').style.width=S.ch[1]/5*100+'%';$('#s1').classList.toggle('on',S.sel===1);$('#s2').classList.toggle('on',S.sel===2)}
function msg(t,ms=420){$('#flash').textContent=t;clearTimeout(flashTimer);flashTimer=setTimeout(()=>$('#flash').textContent='',ms)}
function front(){let a=S.en.filter(e=>!e.dead&&e.z>=S.z-.15);return a.length?Math.min(...a.map(e=>e.z)):1e9}
function advance(n){let b=front(),v=Math.min(n,Math.max(0,b-S.z-.7));S.z+=v;return v}
function hurt(n){n=S.guard?n*.5:n;S.hp-=n;S.dmg+=n;S.hitFlash=.16;if(S.hp<=0){S.hp=0;end(false)}}
function interrupt(e){e.flash=.14;e.knock=.14;if(e.mode==='tell'){e.mode='idle';e.tell=0;e.cool=R(...DEF[e.t].cd)}}
function hit(e,n,skill){if(e.dead)return;e.h-=n;if(skill)interrupt(e);if(e.h<=0){e.dead=true;if(skill){S.finish++;S.win=.3;msg('SKILL FINISH',300)}}}
function fire(k){if(!S.run||S.pause)return;if(S.ch[k-1]<1){msg('ゲージ不足',500);return}S.guard=false;S.ch[k-1]--;S.skill={k,t:0,d:k===1?.42:.50,hit:false};msg(k===1?'水波斬':'天地斬',220)}
function lane(dir){if(S.skill)S.skill=null;if(S.dash)S.dash=null;S.l=C(S.l+dir,0,2)}
function dash(){if(!S.run||S.pause||S.win<=0)return;S.skill=null;S.dash={left:10};S.win=0;msg('SUPER DASH',260)}
function enemyFire(e){let d=DEF[e.t],rel=e.z-S.z;if(d.kind==='ranged'){S.shots.push({l:e.l,z:e.z,d:d.dmg,alive:true,type:e.t,age:0});S.fx.push({type:e.t==='mage'?'cast':'breath',l:e.l,z:e.z,life:.32,max:.32})}else{S.fx.push({type:'enemySlash',l:e.l,z:e.z,life:.30,max:.30,enemy:e.t});if(rel<=1.25&&e.l===S.l)hurt(d.dmg)}e.mode='idle';e.cool=R(...d.cd)}
function step(dt){if(!S.run||S.pause)return;S.time+=dt;S.win=Math.max(0,S.win-dt);S.hitFlash=Math.max(0,S.hitFlash-dt);for(let i=0;i<2;i++){if(S.ch[i]<5){S.frac[i]+=dt/5;while(S.frac[i]>=1&&S.ch[i]<5){S.ch[i]++;S.frac[i]--}}else S.frac[i]=0}if(S.skill){S.skill.t+=dt;let p=S.skill.t/S.skill.d;if(!S.skill.hit&&p>=.30){S.skill.hit=true;let range=S.skill.k===1?1.15:2.15;for(let e of S.en){if(e.dead)continue;let r=e.z-S.z;if(r<0||r>range)continue;if(S.skill.k===1){let ok=S.l===1||(S.l===0&&(e.l===0||e.l===1))||(S.l===2&&(e.l===1||e.l===2));if(ok)hit(e,2,true)}else if(e.l===S.l)hit(e,3,true)}}if(S.skill&&S.skill.t>=S.skill.d)S.skill=null}if(S.dash){let want=42*dt,v=advance(want);S.dash.left-=v;if(v<want-.001||S.dash.left<=0)S.dash=null}else if(!S.guard&&!S.skill)advance(dt/.3);let contact=S.en.filter(e=>!e.dead&&e.l===S.l&&e.z-S.z<=1.05&&e.z-S.z>=-.1).sort((a,b)=>a.z-b.z)[0];if(contact){S.norm+=dt;if(S.norm>=2){S.norm-=2;hit(contact,1,false);contact.knock=.08;S.fx.push({type:'normal',l:S.l,z:S.z+.72,life:.18,max:.18})}}else S.norm=0;for(let e of S.en){if(e.dead)continue;let d=DEF[e.t],rel=e.z-S.z;e.flash=Math.max(0,e.flash-dt);if(e.knock>0){let k=Math.min(dt,e.knock);e.z+=1.4*k;e.knock-=k}if(rel>42||rel<-2)continue;if(e.mode!=='tell'){e.z+=R(-.10,.04)*dt-d.spd*dt;e.move-=dt;if(e.move<=0){if(Math.random()<.58){let o=[-1,1].filter(v=>e.l+v>=0&&e.l+v<=2);if(o.length)e.l+=o[RI(0,o.length-1)]}e.z+=R(-.28,.12);e.move=R(.65,2)}}if(e.mode==='tell'){e.tell-=dt;if(e.tell<=0)enemyFire(e)}else{e.cool-=dt;if(e.cool<=0){e.mode='tell';e.tell=d.tell}}}for(let p of S.shots){if(!p.alive)continue;p.age+=dt;p.z-=18*dt;if(p.z-S.z<=.35){if(p.l===S.l)hurt(p.d);p.alive=false}else if(p.z-S.z<-2)p.alive=false}S.shots=S.shots.filter(p=>p.alive);for(let f of S.fx)f.life-=dt;S.fx=S.fx.filter(f=>f.life>0);if(S.z>=200&&!S.en.some(e=>!e.dead))end(true);else if(S.z>=200)S.z=200;sync()}
function lx(l,z){let p=C(1-z/34,0,1),sp=W*.055+(W*.25-W*.055)*p;return W/2+(l-1)*sp}
function yy(z){let p=C(1-z/34,0,1);return H*.18+(H*.72-H*.18)*p}
function drawBg(){let g=c.createLinearGradient(0,0,0,H);g.addColorStop(0,'#11284b');g.addColorStop(.42,'#584866');g.addColorStop(1,'#493a2e');c.fillStyle=g;c.fillRect(0,0,W,H);let h=H*.18;c.fillStyle='rgba(60,45,40,.65)';c.beginPath();c.moveTo(W*.40,h);c.lineTo(W*.60,h);c.lineTo(W*.95,H);c.lineTo(W*.05,H);c.closePath();c.fill();c.strokeStyle='rgba(255,255,255,.16)';c.lineWidth=1;for(let i=-1;i<=1;i++){c.beginPath();c.moveTo(W/2+i*W*.055,h);c.lineTo(W/2+i*W*.25,H);c.stroke()}for(let z=2;z<34;z+=3){c.strokeStyle='rgba(255,255,255,'+(.03+(1-z/34)*.08)+')';c.beginPath();c.moveTo(lx(0,z)-W*.08,yy(z));c.lineTo(lx(2,z)+W*.08,yy(z));c.stroke()}}
function drawEnemy(e){let r=e.z-S.z,px=lx(e.l,r),py=yy(r),d=DEF[e.t],pers=C(1-r/38,.18,1.12),im=imgs[e.t],tellP=e.mode==='tell'?C(1-e.tell/d.tell,0,1):0;c.save();c.translate(px,py);if(e.mode==='tell'){let pulse=.65+.35*Math.sin(performance.now()/65);c.globalAlpha=.25+.22*pulse;c.fillStyle=(e.t==='mage'||e.t==='dragon')?'#aa72ff':'#ffb0a0';c.beginPath();c.ellipse(0,-d.h*pers*.43,42*pers,55*pers,0,0,Math.PI*2);c.fill();c.globalAlpha=1;c.fillStyle='#fff';c.font=`900 ${Math.max(10,14*pers)}px -apple-system`;c.textAlign='center';c.fillText('攻撃動作',0,-d.h*pers-14*pers)}let dh=d.h*pers,dw=im.complete&&im.naturalWidth?dh*im.naturalWidth/im.naturalHeight:dh*.7;let yOff=0,rot=0,scale=1;if(e.mode==='tell'){if(d.kind==='melee'){yOff=18*pers*tellP;scale=1+.08*tellP;rot=Math.sin(tellP*Math.PI)*.06}else{rot=Math.sin(performance.now()/45)*.025*(.3+tellP);scale=1+.04*tellP}}c.translate(0,yOff);c.rotate(rot);c.scale(scale,scale);if(e.flash>0)c.globalAlpha=.55;if(im.complete&&im.naturalWidth)c.drawImage(im,-dw/2,-dh,dw,dh);c.globalAlpha=1;c.restore();let bw=Math.max(28,Math.min(65,dw*.72));c.fillStyle='#000a';c.fillRect(px-bw/2,py-dh-8*pers+yOff,bw,5*pers);c.fillStyle='#fff';c.fillRect(px-bw/2,py-dh-8*pers+yOff,bw*e.h/e.max,5*pers)}
function drawFx(){for(let f of S.fx){let r=f.z-S.z;if(r<-1||r>38)continue;let px=lx(f.l,r),py=yy(r),p=1-f.life/f.max;c.save();c.translate(px,py);if(f.type==='enemySlash'){c.strokeStyle='#ffdad0';c.shadowColor='#ff6b4a';c.shadowBlur=14;c.lineWidth=6;c.beginPath();c.arc(0,-18,38*C(1-r/38,.25,1),-2.5+p*.8,.4+p*.8);c.stroke()}else if(f.type==='cast'){c.strokeStyle='#c690ff';c.lineWidth=5;c.shadowColor='#a65cff';c.shadowBlur=16;c.beginPath();c.arc(0,-30,22+18*p,0,Math.PI*2);c.stroke()}else if(f.type==='breath'){c.fillStyle='rgba(255,130,55,.55)';c.shadowColor='#ff7a2a';c.shadowBlur=18;c.beginPath();c.moveTo(-12,-26);c.lineTo(12,-26);c.lineTo(34+28*p,6);c.lineTo(-34-28*p,6);c.closePath();c.fill()}else if(f.type==='normal'){c.strokeStyle='#fff';c.lineWidth=4;c.beginPath();c.moveTo(-18,-18);c.lineTo(18,8);c.stroke()}c.restore()}}
function draw(){c.clearRect(0,0,W,H);drawBg();let vis=S.en.filter(e=>!e.dead&&e.z-S.z>-2&&e.z-S.z<38).sort((a,b)=>b.z-a.z);for(let e of vis)drawEnemy(e);drawFx();for(let p of S.shots){let r=p.z-S.z;if(r<0||r>38)continue;let px=lx(p.l,r),py=yy(r)-8;c.save();if(p.type==='mage'){c.fillStyle='#c287ff';c.shadowColor='#9c54ff';c.shadowBlur=20;c.beginPath();c.arc(px,py,11,0,Math.PI*2);c.fill();c.strokeStyle='#ead7ff';c.lineWidth=2;c.beginPath();c.arc(px,py,16+3*Math.sin(performance.now()/60),0,Math.PI*2);c.stroke()}else{let grad=c.createRadialGradient(px,py,2,px,py,18);grad.addColorStop(0,'#fff0b5');grad.addColorStop(.35,'#ff9a3c');grad.addColorStop(1,'rgba(255,60,20,0)');c.fillStyle=grad;c.beginPath();c.arc(px,py,20,0,Math.PI*2);c.fill()}c.restore()}let px=lx(S.l,0),py=H*.72,im=imgs.hero,hh=Math.min(H*.285,238),hw=hh*(im.naturalWidth/Math.max(1,im.naturalHeight)),bob=S.run&&!S.guard?Math.sin(performance.now()/95)*2.2:0;c.save();c.translate(px,py);if(S.guard){c.strokeStyle='#dff7ff';c.lineWidth=5;c.beginPath();c.arc(-hw*.22,-hh*.42,hw*.35,-2.15,2.15);c.stroke()}let heroX=0,heroY=bob,heroRot=0,heroScale=1;if(S.skill){let p=C(S.skill.t/S.skill.d,0,1);if(S.skill.k===1){heroRot=-.10+Math.sin(p*Math.PI)*.20;heroX=Math.sin(p*Math.PI)*12;heroY-=Math.sin(p*Math.PI)*5}else{heroRot=.05*Math.sin(p*Math.PI*2);heroY-=Math.sin(p*Math.PI)*18;heroScale=1+.035*Math.sin(p*Math.PI)}}c.translate(heroX,heroY);c.rotate(heroRot);c.scale(heroScale,heroScale);if(im.complete&&im.naturalWidth)c.drawImage(im,-hw/2,-hh,hw,hh);if(S.skill){let p=S.skill.t/S.skill.d;c.strokeStyle='#e7fbff';c.shadowColor='#82d7ff';c.shadowBlur=20;c.lineWidth=10;c.lineCap='round';if(S.skill.k===1){let a=-2.75+p*3.45;c.beginPath();c.arc(0,-hh*.46,hw*.78,a-.78,a+.78);c.stroke();c.strokeStyle='rgba(120,210,255,.5)';c.lineWidth=20;c.beginPath();c.arc(0,-hh*.46,hw*.72,a-.50,a+.50);c.stroke()}else{let y=-hh*.96+p*hh*.85;c.beginPath();c.moveTo(0,y-35);c.lineTo(0,y+62);c.stroke();c.strokeStyle='rgba(120,210,255,.45)';c.lineWidth=24;c.beginPath();c.moveTo(0,y-18);c.lineTo(0,y+52);c.stroke()}c.shadowBlur=0}c.restore();if(S.win>0){c.fillStyle='#fff';c.font='900 16px -apple-system,sans-serif';c.textAlign='center';c.fillText('↑ SUPER DASH',W/2,H*.55)}if(S.dash){c.strokeStyle='#ffffff66';for(let i=-2;i<=2;i++){c.beginPath();c.moveTo(px+i*12,py+30);c.lineTo(px+i*12,py+130);c.stroke()}}if(S.hitFlash>0){c.fillStyle=`rgba(255,50,40,${.18*(S.hitFlash/.16)})`;c.fillRect(0,0,W,H)}}
function end(ok){S.run=false;S.clear=ok;S.over=!ok;let ts=ok?Math.round(870000*C((75-S.time)/35,0,1)):0,fs=ok?Math.round(80000*C(S.finish/30,0,1)):0,ds=ok?Math.round(50000*C(1-S.dmg/20,0,1)):0;$('#resultTitle').textContent=ok?'STAGE CLEAR':'GAME OVER';$('#resultText').innerHTML='CLEAR TIME '+S.time.toFixed(2)+' s<br>TIME SCORE '+ts.toLocaleString()+'<br>DAMAGE '+S.dmg.toFixed(1)+'<br>DAMAGE SCORE '+ds.toLocaleString()+'<br>SKILL FINISH '+S.finish+' / 30<br>FINISH SCORE '+fs.toLocaleString()+'<br><b>TOTAL '+(ts+fs+ds).toLocaleString()+'</b>';$('#result').classList.remove('hide')}
function start(){reset();S.run=true;last=performance.now();$('#intro').classList.add('hide');msg('スキルを選択 → 画面をタップで攻撃',1000)}
$('#start').onclick=start;$('#retry').onclick=()=>{reset();S.run=true;last=performance.now();$('#result').classList.add('hide');msg('画面タップで攻撃',700)};$('#stop').onclick=e=>{e.preventDefault();if(!S.run)return;S.pause=true;S.guard=false;$('#pause').classList.remove('hide')};$('#resume').onclick=e=>{e.preventDefault();S.pause=false;last=performance.now();$('#pause').classList.add('hide')};$('#s1').onpointerdown=e=>{e.preventDefault();e.stopPropagation();S.sel=1;sync();msg('水波斬を選択：画面をタップで発動',650)};$('#s2').onpointerdown=e=>{e.preventDefault();e.stopPropagation();S.sel=2;sync();msg('天地斬を選択：画面をタップで発動',650)};$('#guard').onpointerdown=e=>{e.preventDefault();e.stopPropagation();if(S.run&&!S.pause)S.guard=true};for(const ev of ['pointerup','pointercancel','pointerleave'])$('#guard').addEventListener(ev,e=>{e.preventDefault();S.guard=false});cv.onpointerdown=e=>{if(S.run&&!S.pause)S.ptr={x:e.clientX,y:e.clientY}};cv.onpointerup=e=>{if(!S.run||S.pause||!S.ptr)return;let dx=e.clientX-S.ptr.x,dy=e.clientY-S.ptr.y,ax=Math.abs(dx),ay=Math.abs(dy),th=28;if(ax<th&&ay<th)fire(S.sel);else if(ax>ay&&ax>th)lane(dx<0?-1:1);else if(ay>ax&&dy<-th)dash();S.ptr=null};document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});reset();function loop(t){let dt=last?Math.min(.033,(t-last)/1000):0;last=t;step(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)
})();