const {createCanvas,loadImage}=require('@napi-rs/canvas'),fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
(async()=>{
const images={};for(const path of ['assets/hero.webp','assets/suraimu.png','assets/がいこつ.png','assets/mahoutukai.png','assets/bonobo.png','assets/minidoragonn.png','hero_body.png.png','hero_arm1.png','hero_arm2.png','hero_hand.png','hero_shoulder.png','assets/hero_sword_motion.png','assets/forest-background.webp','assets/hero-motion-sheet.png']){let i=await loadImage(require('path').join(__dirname,'..',path));Object.defineProperties(i,{naturalWidth:{value:i.width},naturalHeight:{value:i.height},complete:{value:true}});images[path]=i}
const canvas=createCanvas(390,844),els={};const el=id=>els[id]??=(id==='#game'?canvas:{style:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},setAttribute(){},setPointerCapture(){}});canvas.addEventListener=()=>{};
const context={console,Math,Image:function(){return {set src(p){return Object.assign(this,images[p])}}},innerWidth:390,innerHeight:844,devicePixelRatio:1,performance:{now:()=>1000},addEventListener(){},requestAnimationFrame(){},document:{querySelector:el,addEventListener(){},createElement(){return createCanvas(1,1)}},window:{}};
// Return native decoded images, so drawImage receives native objects.
let order=Object.values(images),at=0;context.Image=function(){const image=order[at++];Object.defineProperty(image,'src',{set(){}});return image};
const src=fs.readFileSync(require('path').join(__dirname,'..','game.js'),'utf8').replace('reset();function loop(t)','window.testGame={get state(){return S},step,fire,reset,draw,depth,depthLimit,MAX_DEPTH,poseFrame,drawPoseFrame};reset();function loop(t)');
vm.runInNewContext(src,context);const g=context.window.testGame;g.reset();let s=g.state;s.run=1;s.en=[{t:'slime',z:4,l:1,hp:2,max:2,dead:0,cd:100,tell:0,mv:100,fl:0}];s.en.push({t:'slime',z:180,l:0,hp:2,max:2,dead:0,cd:100,tell:0,mv:100,fl:0});g.fire(1);assert.equal(s.en[0].hp,2);for(let i=0;i<50;i++)g.step(.016);assert.equal(s.en[0].dead,1);assert.equal(s.combo,1);assert.equal(s.fin,1);let charge=s.ch[0];g.fire(1);g.fire(1);assert.equal(s.ch[0],charge-1);s.pause=1;let time=s.t;g.step(.5);assert.equal(s.t,time);
g.reset();s=g.state;s.run=1;s.en.forEach((e,i)=>{e.z=4+i*4;e.l=i%3});g.depth(g.MAX_DEPTH);for(let i=0;i<20;i++)g.step(.016);assert(s.pd<=g.depthLimit());g.fire(1);for(let i=0;i<25;i++)g.step(.016);g.draw();
g.reset();s=g.state;s.run=1;s.en=[{t:'skeleton',z:4,l:1,hp:6,max:6,dead:0,cd:100,tell:0,mv:100,fl:0},{t:'slime',z:4,l:0,hp:2,max:2,dead:0,cd:100,tell:0,mv:100,fl:0}];g.fire(2);for(let i=0;i<60;i++)g.step(.016);assert.equal(s.en[0].hp,3);assert.equal(s.en[1].hp,2);g.draw();g.reset();s=g.state;s.run=1;const rosterA=s.en.map(e=>[e.t,e.z,e.l]);g.reset();s=g.state;s.run=1;assert.equal(JSON.stringify(rosterA),JSON.stringify(s.en.map(e=>[e.t,e.z,e.l])));let frames=0;while(s.run&&frames++<20000){const target=s.en.filter(e=>!e.dead).sort((a,b)=>a.z-b.z)[0];if(target){s.l=target.l;s.guard=Number(s.shots.some(p=>p.l===s.l&&p.z-s.z-s.pd<2)||target.tell>0&&target.z-s.z-s.pd<1.4);if(target.z-s.z-s.pd<3){if(s.ch[1])g.fire(2);else if(s.ch[0])g.fire(1)}}g.step(1/60)}console.log('run status',s.hp,s.t,s.en.filter(e=>!e.dead).length);assert.equal(s.en.filter(e=>!e.dead).length,0,'Full run must clear');assert(s.hp>0);console.log('FULL RUN',JSON.stringify({time:s.t,hp:s.hp,kills:30,frames}));assert.equal(g.poseFrame(1,.479),3);assert.equal(g.poseFrame(1,.48),4);assert.equal(g.poseFrame(2,.539),11);assert.equal(g.poseFrame(2,.54),12);for(let k=1;k<=2;k++)for(let i=0;i<=100;i++){s.skill={k,t:i/100,d:1};g.draw()}console.log('PASS: 202 pose/effect frames; continent lane and single hit; delayed wave hit, single hit, kill, combo, cast lock, pause, front boundary, real-asset drawing');
})();
